# Generated by Django 2.0 on 2018-11-13 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=500, unique=True)),
                ('team_description', models.TextField(max_length=1024)),
                ('team_logo', models.ImageField(upload_to='')),
                ('team_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_create_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_board_name', models.CharField(max_length=1024, unique=True)),
                ('team_board_description', models.CharField(max_length=1024)),
                ('team_board_completion', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_name', models.CharField(max_length=500, unique=True)),
                ('team_member_attendance', models.PositiveSmallIntegerField()),
                ('team_member_contribution_percentage', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
