# Generated by Django 2.0 on 2018-11-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_newteam_team_team_board_team_member'),
        ('scripts', '0002_team_team_board_team_member'),
    ]

    operations = [
    ]
