# Generated by Django 2.0 on 2018-11-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20181125_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='team_members',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newteamcreation',
            name='team_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newteamcreation',
            name='team_member',
            field=models.ManyToManyField(to='scripts.allMembers'),
        ),
    ]
