# Generated by Django 2.0 on 2018-11-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_auto_20181125_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='team_members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
