# Generated by Django 2.0 on 2018-11-25 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20181125_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newteamcreation',
            name='team_created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newteamcreation',
            name='team_member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
