# Generated by Django 2.0 on 2018-11-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_auto_20181125_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
